eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
server:
  port: 8001

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

spring:
  application:
    name: service-news
  datasource:
      url: jdbc:mysql://39.108.134.71:3306/user?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 016312Aj.713
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      maxIdle: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

logging:
  config: classpath:log4j2.xml